default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: caw
  password: caw,./
  pool: 5
  database: caw-kiosk-logsite-development

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: caw
  password: caw,./
  pool: 5
  database: caw-kiosk-logsite-production
